name: Backend CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Grant execute permission for Gradle wrapper
        run: chmod +x ./gradlew

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Run tests
        run: ./gradlew test

      - name: Build the application with Gradle
        run: ./gradlew build --stacktrace

      - name: Check if JAR file exists
        run: ls -al build/libs

      - name: Build Docker Image
        run: |
          docker build --no-cache -t javaee-backend:latest -f Dockerfile .

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Tag Docker image
        run: |
          docker tag javaee-backend:latest hampuscastle/javaee-backend:${{ github.sha }}

      - name: Push Docker image to Docker Hub
        run: |
          docker push hampuscastle/javaee-backend:${{ github.sha }}